### ISSUE TITLE
No query type 'highlight' defined

### ISSUE THREAD

**Issue by L42y** [katspaugh/tj-mode#17]
After I enable tj-mode, the following message appears on `*Messages*` buffer

`Request failed: ((error http 400) . No query type 'highlight' defined)`

**Comment by katspaugh** [comment]
You need to [enable the `highlight` plugin](https://github.com/katspaugh/tj-mode#how-to-install) in your `.tern-project`. Here are the docs:  http://ternjs.net/doc/manual.html#plugin_third_party

Also take a look at a similar issue here: http://ternjs.net/doc/manual.html#plugin_third_party

**Comment by angelozerr** [comment]
@katspaugh I had a similar problem with tern-lint (even if lint was declared inside .tern-project). The problem was tern-lint had a old version of tern and an other plugin had a new version of tern. After npm install, I had : 
- node_modules
  - tern (0.15.0)
  - tern-lint
    - tern (0.14.0)

I have removed at hand the  tern (0.14.0) from th etern-lint modules and problem dispapeared. Perhaps it's teh same issue?

**Comment by L42y** [comment]
I believe I enabled highlight plugin in my `.tern-project`:

![screen shot 2015-09-15 at 10 50 14 am](https://cloud.githubusercontent.com/assets/284820/9866658/9f520d2c-5b97-11e5-9f02-81671a161798.png)

**Comment by katspaugh** [comment]
I've reproduced the issue. Tern server says `Failed to find plugin highlight.`.
I think something changed in how plugins are hooked in.

**Comment by katspaugh** [comment]
I finally figured out how to connect the plugin to Tern without npm's `peerDependencies`.

Please reinstall from npm (`npm install -g tern-highlight`), it should be working now.
